---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
  namespace: monitoring
spec:
  interval: 30m
  timeout: 10m
  chart:
    spec:
      chart: promtail
      version: ">=6.0.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    config:
      clients:
        - url: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push

    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 50m
        memory: 64Mi

    # Increase inotify limits to handle all pod logs
    initContainer:
      - name: init-inotify
        image: docker.io/busybox:1.33
        imagePullPolicy: IfNotPresent
        command:
          - sh
          - -c
          - sysctl -w fs.inotify.max_user_instances=512
        securityContext:
          privileged: true
