global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Ruby Demo Application metrics
  - job_name: 'ruby-demo-app'
    static_configs:
      - targets: ['ruby-demo-app:4567']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Container Registry metrics (if available)
  - job_name: 'registry'
    static_configs:
      - targets: ['registry:5000']
    metrics_path: '/metrics'
    scrape_interval: 60s
    scrape_timeout: 10s

  # Additional applications can be added here automatically
  # Each app should expose metrics at /metrics endpoint
