apiVersion: batch/v1
kind: CronJob
metadata:
  name: etcd-backup-s3
  namespace: kube-system
spec:
  schedule: "0 2 * * *"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          hostNetwork: true
          nodeSelector:
            node-role.kubernetes.io/control-plane: "true"
          tolerations:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
              effect: NoSchedule
          volumes:
            - name: etcd-data
              hostPath:
                path: /srv/data/k3s/server/db/etcd
                type: Directory
            - name: backup
              emptyDir: {}
          initContainers:
            - name: snapshot
              image: rancher/k3s:latest
              command: ["/bin/sh", "-c"]
              args:
                - |
                  set -euo pipefail
                  TS=$(date -u +%Y%m%dT%H%M%SZ)
                  FILE="/backup/etcd-snapshot-$TS.db"

                  # Create etcd snapshot using k3s etcdctl
                  ETCDCTL_API=3 k3s etcdctl snapshot save "$FILE" \
                    --endpoints=https://127.0.0.1:2379 \
                    --cacert=/srv/data/k3s/server/tls/etcd/server-ca.crt \
                    --cert=/srv/data/k3s/server/tls/etcd/server-client.crt \
                    --key=/srv/data/k3s/server/tls/etcd/server-client.key

                  # Verify snapshot
                  ETCDCTL_API=3 k3s etcdctl snapshot status "$FILE" -w table

                  # Compress snapshot
                  gzip -9 "$FILE"
                  ls -lh /backup
              volumeMounts:
                - name: etcd-data
                  mountPath: /srv/data/k3s/server/db/etcd
                  readOnly: true
                - name: backup
                  mountPath: /backup
              securityContext:
                privileged: true
          containers:
            - name: upload
              image: quay.io/minio/mc:latest
              env:
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: s3-backup
                      key: AWS_ACCESS_KEY_ID
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: s3-backup
                      key: AWS_SECRET_ACCESS_KEY
                - name: AWS_ENDPOINTS
                  valueFrom:
                    secretKeyRef:
                      name: s3-backup
                      key: AWS_ENDPOINTS
              command: ["/bin/sh", "-c"]
              args:
                - |
                  set -euo pipefail
                  mc alias set hetzner "https://${AWS_ENDPOINTS}" "${AWS_ACCESS_KEY_ID}" "${AWS_SECRET_ACCESS_KEY}"
                  mc mb -p "hetzner/lvs-cloud-etcd-backups" || true
                  mc cp /backup/*.db.gz "hetzner/lvs-cloud-etcd-backups/$(date -u +%Y)/$(date -u +%m)/"
                  echo "Uploaded etcd snapshot to S3"
              volumeMounts:
                - name: backup
                  mountPath: /backup
              resources:
                requests:
                  cpu: "25m"
                  memory: "128Mi"
                limits:
                  cpu: "500m"
                  memory: "512Mi"
