replicaCount: 2

image:
  repository: registry.lvs.me.uk/ruby-demo-app
  pullPolicy: IfNotPresent
  tag: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 4567

ingress:
  enabled: true
  className: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: app.lvs.me.uk
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: ruby-demo-app-tls
      hosts:
        - app.lvs.me.uk

resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "1"
    memory: "1Gi"

readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5

livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10

env: []
envFrom: []
