# Markdownlint configuration - Very permissive settings
default: false

# Enable only basic structural rules
MD009: false # Trailing spaces
MD010: false # Hard tabs
MD012: false # Multiple consecutive blank lines
MD013: false # Line length
MD025: false # Multiple top-level headings
MD026: false # Trailing punctuation in heading
MD033: false # Inline HTML
MD034: false # Bare URLs
MD036: false # Emphasis used as heading
MD040: false # Fenced code language
MD041: false # First line should be heading
