plugins:
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Include:
    - '**/*.rb'
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - '.bundle/**/*'
    - 'applications/vsmp-royalties/**/*'

# Layout and formatting
Layout/LineLength:
  Max: 120

Layout/MultilineMethodCallIndentation:
  Enabled: false

# Style preferences for this project
Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

# Metrics - relaxed for monitoring scripts
Metrics/MethodLength:
  Max: 30

Metrics/BlockLength:
  Max: 50
  Exclude:
    - 'config/**/*'

# Security and performance
Security/Eval:
  Enabled: true

Performance/StringReplacement:
  Enabled: true
