apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: redis
      version: ">=20.0.0"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    fullnameOverride: redis

    # Disable authentication for internal use
    # (Authelia will connect without password)
    auth:
      enabled: false

    # Standalone mode (no sentinel/cluster)
    architecture: standalone

    # Master configuration
    master:
      persistence:
        enabled: false  # Sessions are ephemeral

      resources:
        requests:
          cpu: "20m"
          memory: "50Mi"
        limits:
          cpu: "100m"
          memory: "128Mi"

    # Disable replicas
    replica:
      replicaCount: 0

    # Disable metrics for now
    metrics:
      enabled: false
