apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-config
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: monorepo
  path: ./platform/cert-manager-config
  prune: true
  wait: true
  timeout: 5m
  dependsOn:
    - name: cert-manager-install
