apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: platform-secrets
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: monorepo
  path: ./platform/secrets
  prune: true
  wait: false
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: namespaces
