apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: postgresql
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: monorepo
  path: ./platform/postgresql-new
  prune: true
  wait: true
  timeout: 10m
  dependsOn:
    - name: storage-install
