apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: redis
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: monorepo
  path: ./platform/redis
  prune: true
  wait: true
  timeout: 10m
  dependsOn:
    - name: helmrepositories
    - name: storage-install
