apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: storage-install
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: monorepo
  path: ./platform/storage-install
  prune: true
  wait: true
  timeout: 15m
  dependsOn:
    - name: helmrepositories
