apiVersion: batch/v1
kind: CronJob
metadata:
  name: pgdump-s3-cleanup
  namespace: platform
spec:
  schedule: "0 4 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: cleanup
              image: quay.io/minio/mc:latest
              env:
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: s3-backup
                      key: AWS_ACCESS_KEY_ID
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: s3-backup
                      key: AWS_SECRET_ACCESS_KEY
                - name: AWS_ENDPOINTS
                  valueFrom:
                    secretKeyRef:
                      name: s3-backup
                      key: AWS_ENDPOINTS
              command: ["/bin/sh", "-c"]
              args:
                - |
                  set -euo pipefail
                  mc alias set hetzner "https://${AWS_ENDPOINTS}" "${AWS_ACCESS_KEY_ID}" "${AWS_SECRET_ACCESS_KEY}"

                  # Delete files older than 7 days
                  CUTOFF_DATE=$(date -u -d '7 days ago' +%Y%m%dT%H%M%SZ)
                  echo "Deleting PostgreSQL backups older than $CUTOFF_DATE"

                  mc rm --recursive --force --older-than 7d "hetzner/lvs-cloud-pg-backups/" || echo "No old files to delete"

                  echo "Cleanup complete. Current backups:"
                  mc ls --recursive "hetzner/lvs-cloud-pg-backups/"
              resources:
                requests:
                  cpu: "10m"
                  memory: "32Mi"
                limits:
                  cpu: "100m"
                  memory: "128Mi"
