apiVersion: batch/v1
kind: CronJob
metadata:
  name: pgdump-s3
  namespace: platform
spec:
  schedule: "0 1 * * *"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          volumes:
            - name: dump
              emptyDir: {}
          initContainers:
            - name: dump
              image: docker.io/bitnami/postgresql:latest
              env:
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgresql-auth
                      key: postgres-password
              command: ["/bin/bash","-c"]
              args:
                - |
                  set -euo pipefail
                  TS=$(date -u +%Y%m%dT%H%M%SZ)
                  FILE="/dump/pgdumpall-$TS.sql.gz"
                  pg_dumpall -h postgresql.platform.svc.cluster.local -U postgres | gzip -9 > "$FILE"
                  ls -lh /dump
              volumeMounts:
                - name: dump
                  mountPath: /dump
          containers:
            - name: upload
              image: quay.io/minio/mc:latest
              env:
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: s3-backup
                      key: AWS_ACCESS_KEY_ID
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: s3-backup
                      key: AWS_SECRET_ACCESS_KEY
                - name: AWS_ENDPOINTS
                  valueFrom:
                    secretKeyRef:
                      name: s3-backup
                      key: AWS_ENDPOINTS
              command: ["/bin/sh","-c"]
              args:
                - |
                  set -euo pipefail
                  mc alias set hetzner "https://${AWS_ENDPOINTS}" "${AWS_ACCESS_KEY_ID}" "${AWS_SECRET_ACCESS_KEY}"
                  mc mb -p "hetzner/lvs-cloud-pg-backups" || true
                  mc cp /dump/*.gz "hetzner/lvs-cloud-pg-backups/$(date -u +%Y)/$(date -u +%m)/"
                  echo "Backup uploaded successfully"
              volumeMounts:
                - name: dump
                  mountPath: /dump
              resources:
                requests:
                  cpu: "25m"
                  memory: "128Mi"
                limits:
                  cpu: "500m"
                  memory: "512Mi"
