apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: postgresql
      version: ">=15.5.0"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    fullnameOverride: postgresql

    auth:
      existingSecret: postgresql-auth
      secretKeys:
        adminPasswordKey: postgres-password

    primary:
      persistence:
        enabled: true
        storageClass: longhorn
        size: 5Gi
        annotations:
          longhorn.io/recurring-jobs: |
            [
              {"name":"daily-snap","task":"snapshot","cron":"0 2 * * *","retain":7,"concurrency":1,"labels":{"app":"postgresql"}},
              {"name":"weekly-bak","task":"backup","cron":"0 3 * * 0","retain":4,"concurrency":1,"labels":{"app":"postgresql"}}
            ]

      resources:
        requests:
          cpu: "50m"
          memory: "256Mi"
        limits:
          cpu: "500m"
          memory: "1Gi"

      # Custom PostgreSQL configuration
      extendedConfiguration: |
        # Memory Configuration
        shared_buffers = 128MB
        effective_cache_size = 512MB
        maintenance_work_mem = 32MB
        work_mem = 2MB

        # Connection Settings
        max_connections = 100

        # WAL Configuration
        wal_buffers = 8MB
        min_wal_size = 80MB
        max_wal_size = 1GB

        # Query Tuning
        random_page_cost = 1.1
        effective_io_concurrency = 200

        # Logging
        logging_collector = on
        log_destination = 'stderr'
        log_line_prefix = '%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h '
        log_statement = 'none'
        log_min_duration_statement = 1000

    service:
      type: ClusterIP
      ports:
        postgresql: 5432

    metrics:
      enabled: false
      serviceMonitor:
        enabled: false

    volumePermissions:
      enabled: true
