apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vsmp-royalties
  namespace: applications
spec:
  interval: 5m
  chart:
    spec:
      chart: ./applications/vsmp-royalties/chart
      sourceRef:
        kind: GitRepository
        name: monorepo
        namespace: flux-system
      valuesFiles:
        - ./applications/vsmp-royalties/values.yaml
  values:
    image:
      repository: registry.lvs.me.uk/vsmp-royalties # {"$imagepolicy": "flux-system:vsmp-royalties:name"}
      tag: "1.0.48" # {"$imagepolicy": "flux-system:vsmp-royalties:tag"}
    ingress:
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: applications-authelia-forwardauth@kubernetescrd
    worker:
      enabled: true
      replicaCount: 1
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "1000m"
          memory: "1Gi"
      terminationGracePeriodSeconds: 60
      env:
        - name: JOB_CONCURRENCY
          value: "1"
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
