apiVersion: batch/v1
kind: CronJob
metadata:
  name: k3s-sqlite-backup-s3
  namespace: kube-system
spec:
  schedule: "0 3 * * *"  # 3 AM daily
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          hostNetwork: true
          nodeSelector:
            node-role.kubernetes.io/control-plane: "true"
          tolerations:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
              effect: NoSchedule
          volumes:
            - name: k3s-data
              hostPath:
                path: /srv/data/k3s
                type: Directory
            - name: backup
              emptyDir: {}
          initContainers:
            - name: sqlite-backup
              image: alpine:3.19
              command: ["/bin/sh", "-c"]
              args:
                - |
                  set -euo pipefail
                  TS=$(date -u +%Y%m%dT%H%M%SZ)
                  
                  # Install sqlite3
                  apk add --no-cache sqlite
                  
                  # Create backup of SQLite database
                  echo "Creating SQLite backup: k3s-sqlite-$TS"
                  sqlite3 /k3s-data/server/db/state.db ".backup /backup/k3s-sqlite-$TS.db"
                  
                  # Also backup critical files
                  cp /k3s-data/server/token /backup/k3s-token-$TS
                  
                  # Compress backups
                  gzip -9 /backup/k3s-sqlite-$TS.db
                  gzip -9 /backup/k3s-token-$TS
                  
                  echo "Backup files created:"
                  ls -lh /backup/
              volumeMounts:
                - name: k3s-data
                  mountPath: /k3s-data
                  readOnly: true
                - name: backup
                  mountPath: /backup
              securityContext:
                runAsUser: 0
          containers:
            - name: upload
              image: quay.io/minio/mc:latest
              env:
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: s3-backup
                      key: AWS_ACCESS_KEY_ID
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: s3-backup
                      key: AWS_SECRET_ACCESS_KEY
                - name: AWS_ENDPOINTS
                  valueFrom:
                    secretKeyRef:
                      name: s3-backup
                      key: AWS_ENDPOINTS
              command: ["/bin/sh", "-c"]
              args:
                - |
                  set -euo pipefail
                  mc alias set hetzner "https://${AWS_ENDPOINTS}" "${AWS_ACCESS_KEY_ID}" "${AWS_SECRET_ACCESS_KEY}"
                  mc mb -p "hetzner/lvs-cloud-k3s-backups" || true
                  mc cp /backup/*.gz "hetzner/lvs-cloud-k3s-backups/$(date -u +%Y)/$(date -u +%m)/"
                  echo "Uploaded k3s SQLite backup to S3"
              volumeMounts:
                - name: backup
                  mountPath: /backup
              resources:
                requests:
                  cpu: "25m"
                  memory: "128Mi"
                limits:
                  cpu: "500m"
                  memory: "512Mi"