services:
  # Watchtower - Automatic Docker container updates
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=300  # Check every 5 minutes
      - WATCHTOWER_INCLUDE_STOPPED=false
      - WATCHTOWER_REVIVE_STOPPED=false
      - WATCHTOWER_LABEL_ENABLE=true  # Only update containers with watchtower labels
      - WATCHTOWER_DEBUG=true
      - DOCKER_CONFIG=/config
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/watchtower/config:/config:ro  # Mount registry auth config
    labels:
      - 'traefik.enable=false'  # Watchtower doesn't need web access
      - 'com.centurylinklabs.watchtower.enable=false'  # Don't update watchtower itself
    networks:
      - web
      - monitoring

networks:
  web:
    name: web
    external: true
  monitoring:
    name: monitoring
    external: true
