services:
  typescript-app:
    image: registry.lvs.me.uk/typescript-app:latest
    container_name: typescript-app
    restart: unless-stopped
    env_file:
      - .env
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.typescript-app.rule=Host(`app.lvs.me.uk`)'
      - 'traefik.http.routers.typescript-app.entrypoints=websecure'
      - 'traefik.http.routers.typescript-app.tls.certresolver=letsencrypt'
      - 'traefik.http.services.typescript-app.loadbalancer.server.port=4567'
      - 'com.centurylinklabs.watchtower.enable=true'  # Enable Watchtower auto-updates
    networks:
      - web
      - monitoring # Connect to monitoring for metrics

networks:
  web:
    name: web
    external: true
  monitoring:
    name: monitoring
    external: true
