apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 30m
  chart:
    spec:
      chart: longhorn
      version: ">=1.10.0"
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  values:
    persistence:
      defaultClass: true
      defaultClassReplicaCount: 1

    defaultSettings:
      defaultReplicaCount: "1"
      defaultDataPath: /srv/data/longhorn
      backupTarget: s3://lvs-cloud-longhorn-backups@nbg1
      backupTargetCredentialSecret: longhorn-backup
      concurrentReplicaRebuildPerNodeLimit: "1"
      createDefaultDiskLabeledNodes: "false"

    longhornManager:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"

    longhornDriver:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"

  postRenderers:
  - kustomize:
      patches:
        # fix for nginx error due to non-writeable nginx logs
        - |
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: longhorn-ui
            namespace: longhorn-system
          spec:
            template:
              spec:
                # 1) Create writable dirs and chown to the nginx user (uid 101)
                initContainers:
                  - name: prepare-nginx-paths
                    image: busybox:1.36
                    command: ["/bin/sh","-c"]
                    args:
                      - >
                        mkdir -p /var/lib/nginx/tmp /var/log/nginx
                        && chown -R 101:101 /var/lib/nginx /var/log/nginx
                    securityContext:
                      runAsUser: 0
                      runAsGroup: 0
                      allowPrivilegeEscalation: false
                    volumeMounts:
                      - name: nginx-tmp
                        mountPath: /var/lib/nginx
                      - name: nginx-logs
                        mountPath: /var/log/nginx

                # 2) Keep the container non-root and mount the writable dirs
                containers:
                  - name: longhorn-ui
                    securityContext:
                      runAsNonRoot: true
                      runAsUser: 101
                      runAsGroup: 101
                      allowPrivilegeEscalation: false
                    volumeMounts:
                      - name: nginx-tmp
                        mountPath: /var/lib/nginx
                      - name: nginx-logs
                        mountPath: /var/log/nginx

                # 3) Ephemeral volumes backing those paths
                volumes:
                  - name: nginx-tmp
                    emptyDir: {}
                  - name: nginx-logs
                    emptyDir: {}
