---
# NOTE: authelia-secrets secret must be created manually during bootstrap
# kubectl create secret generic authelia-secrets -n default \
#   --from-literal=jwt-secret='GENERATE_RANDOM_64_CHARS' \
#   --from-literal=session-secret='GENERATE_RANDOM_64_CHARS' \
#   --from-literal=storage-encryption-key='GENERATE_RANDOM_64_CHARS'
#
# NOTE: authelia-db secret must be created manually
# kubectl create secret generic authelia-db -n default \
#   --from-literal=password='DB_PASSWORD'
#
# NOTE: authelia-users configmap with users_database.yml must be created
# See: https://www.authelia.com/configuration/first-factor/file/
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia
  namespace: default
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: authelia
      version: ">=0.9.0"
      sourceRef:
        kind: HelmRepository
        name: authelia
        namespace: flux-system
  values:
    domain: lvs.me.uk

    # Disable service links to avoid conflicts with Authelia's config system
    pod:
      kind: Deployment
      replicas: 1
      enableServiceLinks: false

      resources:
        requests:
          cpu: 20m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 128Mi

    # Ingress configuration
    ingress:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      subdomain: auth
      tls:
        enabled: true
        secret: authelia-tls

    # Configure secrets
    secret:
      jwt:
        key: jwt-secret
        value: ""
        filename: jwt
      session:
        key: session-secret
        value: ""
        filename: session
      storageEncryptionKey:
        key: storage-encryption-key
        value: ""
        filename: storageEncryptionKey
      existingSecret: authelia-secrets

    # Authelia configuration
    configMap:
      theme: auto
      default_2fa_method: totp

      # Logging
      log:
        level: info
        format: text

      # Session configuration - use PostgreSQL
      session:
        cookies:
          - domain: lvs.me.uk
            authelia_url: https://auth.lvs.me.uk
            default_redirection_url: https://grafana.lvs.me.uk

        redis:
          enabled: false

        # Use PostgreSQL for sessions
        postgres:
          enabled: true
          host: postgresql.default.svc.cluster.local
          port: 5432
          database: authelia
          schema: public
          username: authelia
          timeout: 5s
          tls:
            enabled: false
          password:
            disabled: false
            key: password
            value: ""
            filename: session-postgres-password
          existingSecret: authelia-db

      # Storage backend - PostgreSQL
      storage:
        postgres:
          enabled: true
          address: "tcp://postgresql.default.svc.cluster.local:5432"
          database: authelia
          schema: public
          username: authelia
          timeout: 5s
          tls:
            enabled: false
          password:
            disabled: false
            key: password
            value: ""
            filename: storage-postgres-password
          existingSecret: authelia-db

      # Authentication backend - file based
      authentication_backend:
        password_reset:
          disable: false

        file:
          enabled: true
          path: /config/users_database.yml
          watch: true
          search:
            email: false
            case_insensitive: false
          password:
            algorithm: argon2
            argon2:
              variant: argon2id
              iterations: 3
              memory: 65536
              parallelism: 4
              key_length: 32
              salt_length: 16

      # Access control
      access_control:
        default_policy: deny
        rules:
          # Allow access to Authelia itself
          - domain: auth.lvs.me.uk
            policy: bypass
          # Require authentication for all other domains
          - domain: "*.lvs.me.uk"
            policy: one_factor

      # Notifier (file-based for now, can be SMTP later)
      notifier:
        filesystem:
          enabled: true
          filename: /config/notification.txt
        smtp:
          enabled: false

      # Identity providers - OpenID Connect
      identity_providers:
        oidc:
          enabled: true
          cors:
            endpoints:
              - authorization
              - token
              - revocation
              - introspection
            allowed_origins_from_client_redirect_uris: true

          clients:
            # Grafana OIDC client
            - client_id: grafana
              client_name: Grafana
              client_secret: "$argon2id$v=19$m=65536,t=3,p=4$PLACEHOLDER"
              public: false
              authorization_policy: one_factor
              redirect_uris:
                - https://grafana.lvs.me.uk/login/generic_oauth
              scopes:
                - openid
                - profile
                - groups
                - email
              userinfo_signed_response_alg: none
              token_endpoint_auth_method: client_secret_basic

      # Regulation (brute force protection)
      regulation:
        max_retries: 3
        find_time: 2m
        ban_time: 5m

    # Mount users database from ConfigMap
    persistence:
      enabled: false

    configMapVolumes:
      - name: authelia-users
        mountPath: /config/users_database.yml
        subPath: users_database.yml
