---
# Traefik ForwardAuth middleware for Authelia SSO
# Apply this middleware to any IngressRoute or Ingress that requires authentication
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: authelia-forwardauth
  namespace: default
spec:
  forwardAuth:
    address: http://authelia.default.svc.cluster.local/api/authz/forward-auth
    trustForwardHeader: true
    authResponseHeaders:
      - Remote-User
      - Remote-Groups
      - Remote-Email
      - Remote-Name
