---
# Traefik ForwardAuth middleware for Authelia SSO
# Apply this middleware to any Ingress/IngressRoute that requires authentication
# DO NOT apply to Authelia's own ingress
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: authelia-forwardauth
  namespace: default
spec:
  forwardAuth:
    address: http://authelia.default.svc.cluster.local/api/authz/forward-auth
    trustForwardHeader: true
    authResponseHeaders:
      - Remote-User
      - Remote-Groups
      - Remote-Email
      - Remote-Name
