source 'https://rubygems.org'

ruby '~> 3.2.0'

gem 'sinatra', '~> 3.0'
gem 'puma', '~> 6.0'
gem 'prometheus-client', '~> 4.0'
gem 'httparty', '~> 0.21'

group :development, :test do
  gem 'rspec', '~> 3.12'
end