---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: source-controller-data
  namespace: flux-system
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path  # K3s default local storage
  resources:
    requests:
      storage: 10Gi
