# frozen_string_literal: true

source 'https://rubygems.org'

ruby '~> 3.3.0'

gem 'httparty', '~> 0.21'
gem 'json', '~> 2.6'
gem 'opentelemetry-exporter-otlp', '~> 0.26'
gem 'opentelemetry-instrumentation-http', '~> 0.23'
gem 'opentelemetry-instrumentation-sinatra', '~> 0.23'
gem 'opentelemetry-sdk', '~> 1.4'
gem 'prometheus-client', '~> 4.0'
gem 'puma', '~> 6.0'
gem 'sinatra', '~> 3.0'

group :development, :test do
  gem 'rspec', '~> 3.12'
  gem 'rubocop', '~> 1.57'
  gem 'rubocop-performance', '~> 1.19'
end
