apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - namespace.yaml
  - helmrelease.yaml
  # - clusterissuers.yaml  # Apply manually after cert-manager CRDs are installed
