---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: alloy
      version: ">=0.9.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    alloy:
      configMap:
        create: false
        name: alloy-config
        key: config.alloy

      clustering:
        enabled: false

      stabilityLevel: "generally-available"

    controller:
      type: daemonset

      # Mount host paths for log collection
      volumes:
        extra:
          - name: varlog
            hostPath:
              path: /var/log
          - name: varlibdockercontainers
            hostPath:
              path: /var/lib/rancher/k3s/agent/containerd

      volumeMounts:
        extra:
          - name: varlog
            mountPath: /var/log
            readOnly: true
          - name: varlibdockercontainers
            mountPath: /var/lib/rancher/k3s/agent/containerd
            readOnly: true

    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi

    # Run with privileges to read logs
    securityContext:
      privileged: true
      runAsUser: 0

    serviceMonitor:
      enabled: false
