---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: grafana
      version: ">=8.0.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    replicas: 1

    admin:
      existingSecret: grafana-admin
      userKey: admin-user
      passwordKey: admin-password

    env:
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_INSTALL_PLUGINS: "grafana-clock-panel"
      GF_SERVER_ROOT_URL: "https://grafana.lvs.me.uk"

    persistence:
      enabled: true
      storageClassName: longhorn
      size: 5Gi
      annotations:
        longhorn.io/recurring-jobs: |
          [
            {"name":"daily-snap","task":"snapshot","cron":"0 2 * * *","retain":7,"concurrency":1,"labels":{"app":"grafana"}},
            {"name":"weekly-bak","task":"backup","cron":"0 3 * * 0","retain":4,"concurrency":1,"labels":{"app":"grafana"}}
          ]

    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi

    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Mimir
            type: prometheus
            access: proxy
            url: http://mimir.monitoring.svc.cluster.local:8080/prometheus
            isDefault: true
            editable: true

          - name: Loki
            type: loki
            access: proxy
            url: http://loki.monitoring.svc.cluster.local:3100
            editable: true

          - name: Tempo
            type: tempo
            access: proxy
            url: http://tempo.monitoring.svc.cluster.local:3100
            editable: true

    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: 'default'
            orgId: 1
            folder: ''
            type: file
            disableDeletion: false
            updateIntervalSeconds: 10
            allowUiUpdates: true
            options:
              path: /var/lib/grafana/dashboards/default

    dashboardsConfigMaps:
      default: grafana-dashboards

    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
        - grafana.lvs.me.uk
      path: /
      pathType: Prefix
      tls:
        - secretName: grafana-tls
          hosts:
            - grafana.lvs.me.uk

    serviceMonitor:
      enabled: false

    testFramework:
      enabled: false
