---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mimir
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: mimir-distributed
      version: ">=5.0.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    # Run in monolithic mode (single instance)
    deploymentMode: SingleBinary

    mimir:
      structuredConfig:
        multitenancy_enabled: false

        limits:
          max_global_series_per_user: 150000
          max_global_series_per_metric: 20000
          ingestion_rate: 10000
          ingestion_burst_size: 200000

    mimir-distributed:
      enabled: true

    # Single binary configuration
    nginx:
      enabled: false

    rollout_operator:
      enabled: false

    # Storage configuration
    metaMonitoring:
      serviceMonitor:
        enabled: false

    # Single binary with persistence
    persistence:
      enabled: true
      storageClass: longhorn
      size: 10Gi
      annotations:
        longhorn.io/recurring-jobs: |
          [
            {"name":"daily-snap","task":"snapshot","cron":"0 2 * * *","retain":7,"concurrency":1,"labels":{"app":"mimir"}},
            {"name":"weekly-bak","task":"backup","cron":"0 3 * * 0","retain":4,"concurrency":1,"labels":{"app":"mimir"}}
          ]

    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 1000m
        memory: 512Mi
