---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: tempo
      version: ">=1.10.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    tempo:
      repository: grafana/tempo

      storage:
        trace:
          backend: local
          local:
            path: /var/tempo/traces
          wal:
            path: /var/tempo/wal

      metricsGenerator:
        enabled: true
        remoteWriteUrl: http://mimir.monitoring.svc.cluster.local:8080/api/v1/push

    persistence:
      enabled: true
      storageClassName: longhorn
      size: 5Gi
      annotations:
        longhorn.io/recurring-jobs: |
          [
            {"name":"daily-snap","task":"snapshot","cron":"0 2 * * *","retain":7,"concurrency":1,"labels":{"app":"tempo"}},
            {"name":"weekly-bak","task":"backup","cron":"0 3 * * 0","retain":4,"concurrency":1,"labels":{"app":"tempo"}}
          ]

    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi

    service:
      type: ClusterIP

    serviceMonitor:
      enabled: false
