# DEPRECATED: This workflow is replaced by deploy-applications.yml
# The new workflow handles all applications dynamically
#
# This file remains for now but will be removed once the new workflow is verified
# All application deployments now use the deploy-applications.yml workflow

name: '[DEPRECATED] Build and Deploy Ruby App'

on:
  push:
    branches: [master]
    paths:
      - 'applications/ruby-demo-app/**' # User app path (unchanged)
  pull_request:
    branches: [master]
    paths:
      - 'applications/ruby-demo-app/**' # User app path (unchanged)

concurrency:
  group: deploy-ruby-app-${{ github.ref }}
  cancel-in-progress: false

env:
  REGISTRY_URL: registry.lvs.me.uk
  IMAGE_NAME: ruby-demo-app # Updated name

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_URL }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./applications/ruby-demo-app # Updated path
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=ruby-demo-app
          cache-to: type=gha,mode=max,scope=ruby-demo-app

  # NOTE: Deployment is now handled by deploy-applications.yml workflow
  # This workflow will be removed once the new dynamic workflow is verified
